stages:
  prepare:
    cmd: python src/prepare.py data/data.xml
    deps:
    - src/prepare.py
    outs:
    - data/prepared
  train:
    cmd: python src/train.py data/trained model.pkl
    deps:
    - data/prepared
    - src/train.py
    params:
    - train.layers_count
    outs:
    - data/trained
    - metrics.json
  evaluate:
    cmd: python src/evaluate.py model.pkl data/features
    deps:
    - data/trained
    - src/evaluate.py
    outs:
    - eval
metrics:
- metrics.json
plots:
- eval/plots/images/loss.png
- dvclive/plots/custom/iris.json:
    x: epoch
    y: loss
    title: Training and validation loss
